import asyncio
import math
from dataclasses import dataclass

from stompman.connection_manager import ConnectionManager
from stompman.errors import ConnectionLostError, SendReceiptError
from stompman.frames import ErrorFrame, SendFrame
from stompman.receipts import PendingReceipt, PendingReceipts, ReceiptFailureReason, make_receipt_id, wait_for_result


@dataclass(kw_only=True, slots=True, frozen=True)
class _SendConfirmation:
    receipts: PendingReceipts

    def confirm(self, pending: PendingReceipt) -> None:
        self.receipts.discard(pending.receipt_id)
        if not pending.result.done():
            pending.result.set_result(None)

    def fail_on_error_frame(self, pending: PendingReceipt, frame: ErrorFrame) -> None:
        self.fail(pending, "rejected", frame=frame)

    def fail_on_connection_loss(self, pending: PendingReceipt) -> None:
        self.fail(pending, "connection_lost")

    def fail(
        self, pending: PendingReceipt, reason: ReceiptFailureReason, *, frame: ErrorFrame | None = None
    ) -> SendReceiptError:
        self.receipts.discard(pending.receipt_id)
        if pending.result.done() and isinstance(existing := pending.result.result(), SendReceiptError):
            return existing
        error = SendReceiptError(receipt_id=pending.receipt_id, reason=reason, frame=frame)
        if not pending.result.done():
            pending.result.set_result(error)
        return error


def _is_confirmed(pending: PendingReceipt) -> bool:
    return pending.result.done() and pending.result.result() is None


async def send_with_receipt(
    *,
    connection_manager: ConnectionManager,
    receipts: PendingReceipts,
    receipt_timeout: float,
    body: bytes,
    destination: str,
    content_type: str | None,
    add_content_length: bool,
    headers: dict[str, str] | None,
) -> None:
    if not math.isfinite(receipt_timeout) or receipt_timeout <= 0:
        msg = "receipt_timeout must be a finite positive number"
        raise ValueError(msg)
    if headers and "receipt" in headers:
        msg = "receipt header is generated by the client when receipt_timeout is set"
        raise ValueError(msg)

    connection_state = await connection_manager._get_restored_connection_state()
    loop = asyncio.get_running_loop()
    confirmation = _SendConfirmation(receipts=receipts)
    pending = PendingReceipt(
        waiter=confirmation,
        connection=connection_state.connection,
        receipt_id=make_receipt_id(),
        epoch=connection_manager._reconnection_count,
        deadline=loop.time() + receipt_timeout,
        result=loop.create_future(),
    )
    receipts.add(pending)

    try:
        async with asyncio.timeout_at(pending.deadline):
            await connection_state.connection.write_frame(
                SendFrame.build(
                    body=body,
                    destination=destination,
                    transaction=None,
                    content_type=content_type,
                    add_content_length=add_content_length,
                    headers={**(headers or {}), "receipt": pending.receipt_id},
                )
            )
    except TimeoutError as error:
        # The frame is fully buffered before draining, so a receipt can win this race.
        if _is_confirmed(pending):
            return
        raise confirmation.fail(pending, "timeout") from error
    except ConnectionLostError as error:
        await connection_manager._discard_failed_connection_state(connection_state, error)
        if _is_confirmed(pending):
            return
        raise confirmation.fail(pending, "connection_lost") from error
    except BaseException:
        receipts.discard(pending.receipt_id)
        raise

    await _await_receipt(pending, confirmation)


async def _await_receipt(pending: PendingReceipt, confirmation: _SendConfirmation) -> None:
    try:
        error = await wait_for_result(pending)
    except TimeoutError as timeout_error:
        raise confirmation.fail(pending, "timeout") from timeout_error
    except asyncio.CancelledError:
        confirmation.receipts.discard(pending.receipt_id)
        raise
    if error is not None:
        raise error
