"""Compatibility exports for :mod:`stompman.core.serde`."""

from .core.serde import (
    BACKSLASH,
    CARRIAGE,
    COLON_,
    COMMANDS_TO_FRAMES,
    FRAMES_TO_COMMANDS,
    FRAMES_WITH_BODY,
    HEADER_ESCAPE_CHARS,
    HEADER_UNESCAPE_CHARS,
    NEWLINE,
    NULL,
    FrameParser,
    _unescape_header_part,
    dump_frame,
    dump_header,
    iter_bytes,
    make_frame_from_parts,
    parse_header,
    unescape_byte,
)

__all__ = [
    "BACKSLASH",
    "CARRIAGE",
    "COLON_",
    "COMMANDS_TO_FRAMES",
    "FRAMES_TO_COMMANDS",
    "FRAMES_WITH_BODY",
    "HEADER_ESCAPE_CHARS",
    "HEADER_UNESCAPE_CHARS",
    "NEWLINE",
    "NULL",
    "FrameParser",
    "_unescape_header_part",
    "dump_frame",
    "dump_header",
    "iter_bytes",
    "make_frame_from_parts",
    "parse_header",
    "unescape_byte",
]
