services:
  activemq-artemis:
    image: apache/activemq-artemis:2.37.0-alpine
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: ":=123"
    ports:
      - 9000:61616

  activemq-classic:
    image: apache/activemq-classic:6.1.2
    environment:
      ACTIVEMQ_CONNECTION_USER: admin
      ACTIVEMQ_CONNECTION_PASSWORD: ":=123"
    ports:
      - 9001:61613
