[project]
name = "stompman-workspace"
requires-python = ">=3.11"
version = "0"

[dependency-groups]
dev = [
    "anyio==4.14.2",
    "faker==40.37.0",
    "hypothesis==6.165.10",
    "mypy==2.3.1",
    "polyfactory==3.3.0",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "pytest-timeout==2.4.0",
    "ruff==0.16.5",
    "uvloop==0.22.1",
]
ws = [
    "websockets==17.1",
]

[tool.uv]
package = false

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
stompman = { workspace = true }


[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
strict = true

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "async-function-with-timeout",
    "missing-trailing-comma",
    "missing-copyright-notice",
    "D1",
    "incorrect-blank-line-before-class",
    "multi-line-summary-second-line",
    "docstring-missing-returns",
    "docstring-missing-exception",
    "single-line-implicit-string-concatenation",
    "import-private-name",
    "unnecessary-dunder-call",
    "too-many-arguments",
    "private-member-access"
]
extend-per-file-ignores = { "*/test_*/*" = ["assert", "private-member-access", "ARG", "no-self-use", "magic-value-comparison", "unused-async", "pytest-raises-with-multiple-statements", "boolean-type-hint-positional-argument"] }

[tool.pytest.ini_options]
addopts = "--cov -s -vv"

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_also = ["if TYPE_CHECKING:"]
